### ISSUE TITLE
Still having SSH problems

### ISSUE THREAD

**Issue by madphill** [fdac20/Practice0#33]
I am able to connect to da2, but I can't point to localhost successfully. Here's my ssh setup:
![ssh_setup](https://user-images.githubusercontent.com/54443741/91565795-c0b41f80-e910-11ea-9670-2fce0b63e832.JPG)
Pointing to port 8888 doesn't work for me, I get this error:
![8888_denied](https://user-images.githubusercontent.com/54443741/91565794-c01b8900-e910-11ea-96c9-9479188350b1.JPG)
Connecting to 8889 works fine for me, so that's what I have in my ssh setup. However, when I point my browser to http://localhost:8889, I get a no data in my browser and a connection refused error on the terminal. Any pointers?
![localhost_no_data](https://user-images.githubusercontent.com/54443741/91565792-c01b8900-e910-11ea-9d06-15650ef6d0e4.JPG)
![connection_refused](https://user-images.githubusercontent.com/54443741/91565796-c0b41f80-e910-11ea-8e35-21bcf81d2763.JPG)

**Comment by audrism** [comment]
Have you tried -L8889:localhost:8888

and connect via browser to localhost:8889?

I tried your container and it seems to work fine. 

You probably already have jupyter running on your laptop, thats why port 8888 can not be reassigned. 
You can eaiter stop that notebook server or use port 8889. Please keep in mind that on the docker container it
jupyter listens on 8888, so -L8889:localhost:8889 connects to nothing.

**Comment by madphill** [comment]
Ah, thanks for the help! -L8889:localhost:8888 worked for me.
