### ISSUE TITLE
Practice 0: Cant connect to Jupyer notebook via localhost

### ISSUE THREAD

**Issue by Boostem** [fdac20/Practice0#63]
Hello, I am having trouble connecting to Localhost:8888. I can ssh to my docker container just fine. 

I have renamed my notebook file to <mynetid> from practice0, did a PR 8 days ago but I am still unable to connect to my notebook.

I type jupyter notebook in my docker but the :8888 port is already in use, so I have been unable to connect via my localhost:8888.

I have added my public key to my own GitHub and I added my key to my .md PR a few weeks back.

**Comment by audrism** [comment]
If 8888 is already in use on your laptop, please use another port, e.g., 8898

Please make sure only the first port is changed, as on the docker container it stays as 8888

**Comment by Boostem** [comment]
OK, thank you.
